apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  influxdb.conf: |
    ### Welcome to the InfluxDB configuration file.
    ### this is management by configMaps.
    reporting-disabled = true

    [meta]
      enabled = true
      dir = "/var/lib/influxdb/meta"

      bind-address = ":8088"
      retention-autocreate = true
      election-timeout = "1s"
      heartbeat-timeout = "1s"
      leader-lease-timeout = "1m0s"
      commit-timeout = "500ms"
      cluster-tracing = false

    [data]
      enabled = true
      dir = "/var/lib/influxdb/data"
      max-wal-size = 104857600 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
      wal-flush-interval = "10m" # Maximum time data can sit in WAL before a flush.
      wal-partition-flush-delay = "2s" # The delay time between each WAL partition being flushed.
      wal-dir = "/var/lib/influxdb/wal"
      wal-logging-enabled = true
      data-logging-enabled = true

      # wal-ready-series-size = 25600
      # wal-compaction-threshold = 0.6
      # wal-max-series-size = 2097152
      # wal-flush-cold-interval = "10m"
      # wal-partition-size-threshold = 20971520
      # query-log-enabled = true
      cache-max-memory-size = 524288000
      cache-snapshot-memory-size = 26214400
      cache-snapshot-write-cold-duration = "1h"
      compact-min-file-count = 3
      compact-full-write-cold-duration = "24h"
      # max-points-per-block = 1000

    [hinted-handoff]
      enabled = true
      dir = "/var/lib/influxdb/hh"
      max-size = 1073741824
      max-age = "168h"
      retry-rate-limit = 0
      retry-interval = "1s"
      retry-max-interval = "1m"
      purge-interval = "1h"

    [retention]
      enabled = true
      check-interval = "30m"

    [shard-precreation]
      enabled = true
      check-interval = "10m"
      advance-period = "30m"

    [monitor]
      store-enabled = true # Whether to record statistics internally.
      store-database = "_internal" # The destination database for recorded statistics
      store-interval = "10s" # The interval at which to record statistics

    [http]
      enabled = true
      bind-address = ":8086"
      auth-enabled = true
      log-enabled = true
      write-tracing = false
      pprof-enabled = false
      max-row-limit = 10000
      realm = "InfluxDB"

    [subscriber]
      enabled = true
      http-timeout = "30s"

    [continuous_queries]
      log-enabled = true
      enabled = true
      run-interval = "1m"
